# Generated by Django 4.2.7 on 2023-11-02 12:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_alter_application_photo_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='photo_file',
            field=models.ImageField(upload_to='image/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])]),
        ),
    ]
