# Generated by Django 4.2.7 on 2023-11-02 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_request'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
