# Generated by Django 4.2.7 on 2023-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0007_delete_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'Принято в работу'), ('COMPLETED', 'Выполнено')], default='NEW', max_length=254, verbose_name='Статус'),
        ),
    ]
