# Generated by Django 4.2.7 on 2023-11-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_remove_application_user_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('N', 'Новая'), ('P', 'Принято в работу'), ('C', 'Выполнено')], default='N', max_length=254, verbose_name='Статус'),
        ),
    ]
